build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,9 +5,8 @@ on:
   schedule:
     - cron: '00 0 * * *'
 
-permissions:  #  <--  Same level as 'on:' and 'jobs:'
+permissions:
   releases: write
-
 
 jobs:
   build:
@@ -18,7 +17,7 @@ jobs:
         run: |
           sudo apt update
           sudo apt install -y wget apktool zipalign apksigner jq openjdk-17-jdk
-      - name: Set JAVA_HOME
+      - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
@@ -30,9 +29,8 @@ jobs:
       - name: Download IceRaven APK
         run: |
           wget -q "https://github.com/fork-maintainers/iceraven-browser/releases/download/iceraven-${{ env.ICERAVEN_VERSION }}/iceraven-${{ env.ICERAVEN_VERSION }}-browser-arm64-v8a-forkRelease.apk" -O iceraven.apk
-
       - name: Run Build Script
-        run: bash build.sh ${{ env.ICERAVEN_VERSION }}
+        run: bash build.sh ${{ env.ICERAVEN_VERSION }} || { echo "Build script failed"; exit 1; }  # Fail the workflow if the script fails
       - name: Sign APK
         run: |
           echo "${{ secrets.KEYSTORE }}" | base64 -di > keystore.jks
