build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,7 @@
 concurrency:
   group: ${{ github.workflow }}
   cancel-in-progress: true
+
 name: Build IceRaven Dark Theme
 
 on:
@@ -33,7 +34,7 @@ jobs:
         run: |
           wget -q "https://github.com/fork-maintainers/iceraven-browser/releases/download/iceraven-${{ env.ICERAVEN_VERSION }}/iceraven-${{ env.ICERAVEN_VERSION }}-browser-arm64-v8a-forkRelease.apk" -O iceraven.apk
       - name: Run Build Script
-        run: bash build.sh ${{ env.ICERAVEN_VERSION }} || { echo "Build script failed"; exit 1; }  # Fail the workflow if the script fails
+        run: bash build.sh ${{ env.ICERAVEN_VERSION }} || { echo "Build script failed"; exit 1; }
       - name: Sign APK
         run: |
           echo "${{ secrets.KEYSTORE }}" | base64 -di > keystore.jks
